@startuml
class EventureApi {
    +string Url
    +GetData()
    -string secretKey
}

class AuthService {
    +string AuthUrl
    +Login()
    -string password
}

EventureApi -> AuthService : Uses
@enduml